import type { Product } from "@/types/product";

export const mockProducts: readonly Product[] = [
  {
    id: "mock-001",
    code: "BP-001",
    name: "Relief Sun Rice + Probiotics",
    brand: "Beauty of Joseon",
    category: "Skincare",
    description:
      "Protector solar ligero con acabado hidratante. Ideal para uso diario y sin residuo blanco.",
    variant: "50 ml",
    priceBob: 168,
    priceValidUntil: "27 julio, 08:15",
    availability: "available",
    color: "rose",
    visual: "tube",
  },
  {
    id: "mock-002",
    code: "BP-002",
    name: "The Star Chapter: SANCTUARY",
    brand: "TXT",
    category: "K-pop",
    description:
      "Álbum original en versión especial. Incluye photobook, CD y beneficios según disponibilidad.",
    variant: "Versión Angel",
    priceBob: 245,
    priceValidUntil: "27 julio, 08:15",
    availability: "reserved",
    color: "lilac",
    visual: "album",
  },
  {
    id: "mock-003",
    code: "BP-003",
    name: "Heartleaf Calming Mask",
    brand: "Abib",
    category: "Skincare",
    description:
      "Mascarilla de hoja calmante con heartleaf para refrescar la piel después de un día largo.",
    variant: "1 unidad",
    priceBob: 39,
    priceValidUntil: "Precio por actualizar",
    availability: "expired",
    color: "mint",
    visual: "mask",
  },
  {
    id: "mock-004",
    code: "BP-004",
    name: "Juicy Lasting Tint",
    brand: "rom&nd",
    category: "Maquillaje",
    description: "Tinte de labios de larga duración con brillo jugoso y color modulable.",
    variant: "N.º 23 Nucadamia",
    priceBob: 119,
    priceValidUntil: "27 julio, 08:15",
    availability: "available",
    color: "peach",
    visual: "lip",
  },
  {
    id: "mock-005",
    code: "BP-005",
    name: "Dive-In Hyaluronic Serum",
    brand: "Torriden",
    category: "Skincare",
    description:
      "Sérum hidratante de textura acuosa con ácido hialurónico de bajo peso molecular.",
    variant: "50 ml",
    priceBob: 182,
    priceValidUntil: "27 julio, 08:15",
    availability: "sold_out",
    color: "sky",
    visual: "bottle",
  },
  {
    id: "mock-006",
    code: "BP-006",
    name: "Mini peluche Ddungie",
    brand: "BT21",
    category: "Merch",
    description: "Mini peluche oficial, suave y fácil de llevar como compañero de viaje.",
    variant: "12 cm",
    priceBob: 154,
    priceValidUntil: "27 julio, 08:15",
    availability: "available",
    color: "cream",
    visual: "plush",
  },
];

export function findMockProduct(id: string | null): Product {
  return mockProducts.find((product) => product.id === id) ?? mockProducts[0]!;
}
